apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "anarchy.name" . }}
  namespace: {{ include "anarchy.namespaceName" . }}
  labels:
    {{- include "anarchy.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "anarchy.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "anarchy.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
      - name: manager
        env:
        - name: ANARCHY_SERVICE
          value: {{ include "anarchy.name" . }}
        - name: CALLBACK_BASE_URL
          value: https://{{ include "anarchy.hostname" . }}
        - name: RUNNER_IMAGE
          value: {{ include "anarchy.runner.image" . }}
        - name: RUNNER_IMAGE_PULL_POLICY
          value: {{ .Values.image.anarchyRunner.pullPolicy }}
        image: {{ include "anarchy.operator.image" . }}
        imagePullPolicy: {{ .Values.image.anarchyOperator.pullPolicy }}
        {{- with .Values.image.anarchyOperator.livenessProbe }}
        livenessProbe:
					{{- toYaml . | nindent 10 }}
        {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      restartPolicy: Always
      securityContext: {}
      serviceAccountName: {{ include "anarchy.serviceAccountName" . }}
      terminationGracePeriodSeconds: 30
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
