---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "anarchy.serviceAccountName" . }}
  namespace: {{ include "anarchy.namespaceName" . }}
  labels:
    {{- include "anarchy.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: anarchy
subjects:
- kind: ServiceAccount
  name: {{ include "anarchy.serviceAccountName" . }}
