{{- if .Values.openshift.enabled -}}
{{- $name := include "anarchy.name" . -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ $name }}
  namespace: {{ include "anarchy.namespaceName" . }}
spec:
  host: {{ include "anarchy.hostname" . }}
  port:
    targetPort: api
  tls:
    termination: edge
  to:
    kind: Service
    name: {{ $name }}
{{- end }}
