apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: anarchyactions.anarchy.gpte.redhat.com
spec:
  group: anarchy.gpte.redhat.com
  scope: Namespaced
  names:
    plural: anarchyactions
    singular: anarchyaction
    kind: AnarchyAction
    shortNames: []
  versions:
  - name: v1
    served: true
    storage: true
    subresources:
      status: {}
    additionalPrinterColumns:
    - name: Governor
      type: string
      jsonPath: .spec.governorRef.name
    - name: Subject
      type: string
      jsonPath: .spec.subjectRef.name
    - name: Action
      type: string
      jsonPath: .spec.action
    - name: After
      type: string
      jsonPath: .spec.after
    - name: Run
      type: string
      jsonPath: .status.runRef.name
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp
    schema:
      openAPIV3Schema:
        description: >-
          AnarchySubjects track state Anarchy. Subjects represent something that is managed.
          When Anarchy ansible processing runs it always runs for a subject and can update
          the subject during the run to reflect state changes.
        type: object
        required:
        - apiVersion
        - kind
        - metadata
        - spec
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            description: >-
              Definition of the AnarchyAction.
            type: object
            required:
            - action
            - subjectRef
            properties:
              action:
                description: >-
                  Name of action from AnarchyGovernor used to process AnsibleRun
                type: string
              after:
                description: >-
                  Datetime string in for format "YYYY-MM-DDThh:mm:ssZ". AnarchyRun will be created
                  for the AnarchyAction after this time.
                type: string
              callbackToken:
                description: Random string used to validate callbacks
                type: string
              governorRef:
                description: Reference to controlling AnarchyGovernor
                type: object
                required:
                - name
                properties:
                  apiVersion:
                    type: string
                  kind:
                    type: string
                  name:
                    type: string
                  namespace:
                    type: string
                  uid:
                    type: string
              subjectRef:
                description: Reference to owning AnarchySubject
                type: object
                required:
                - name
                properties:
                  apiVersion:
                    type: string
                  kind:
                    type: string
                  name:
                    type: string
                  namespace:
                    type: string
                  uid:
                    type: string
          status:
            description: >-
              AnarchyAction status.
            type: object
            properties:
              callbackEvents:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    data:
                      type: object
                      x-kubernetes-preserve-unknown-fields: true
                    name:
                      type: string
              runRef:
                type: object
                properties:
                  apiVersion:
                    type: string
                  kind:
                    type: string
                  name:
                    type: string
                  namespace:
                    type: string
                  uid:
                    type: string
              runScheduled:
                type: string
